
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mariunda
 */
public class GraphicalProtein extends javax.swing.JPanel {
    
    ArrayList<PeptideCoincidence> listPeptides = new ArrayList<>();
    Fasta fasta = new Fasta();
    
    /**
     * Creates new form graphicalProtein
     */
    public GraphicalProtein() {
        initComponents();
    }
    
    // Function to receive the fasta and the array of peptides
    public void updateData (Fasta f, ArrayList<PeptideCoincidence> a) {
        fasta = f;
        listPeptides = a;
    }
    
 @Override
    public void paintComponent(Graphics g) {
      
        super.paintComponent(g);
        g.setColor(Color.white);
        
        // Set the protein bar representation size to the windows size minus 20
        int maxWidth = this.getWidth()-20;
        
        // Draw the rectangle when the peptides are going to be drawn
        g.fillRect(0, 10, maxWidth, 30);
        g.setColor(Color.black);
        g.drawRect(0, 10, maxWidth, 30);
        
        // Set the color for drawing the peptide representation
        g.setColor(Color.blue);
        // Draw the representation only if there are peptides
        for (int i = 0; i < listPeptides.size(); i++) {
            // Draw each peptide
            PeptideCoincidence peptide = listPeptides.get(i);
            
            int x_start = Math.floorDiv(peptide.getStart()*maxWidth, fasta.getLength());
            int x_length = Math.floorDiv(peptide.getLength()*maxWidth, fasta.getLength());
            
            System.out.println(i + " " + x_start + " " + x_length);
            g.fillRect(x_start, 10, x_length, 30);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
